class ProjectSerializer < ActiveModel::Serializer
  attributes(
    *%i[
      id
      name
      owner
      repo
      stars_count
      forks_count
      contributors_count
      views_count
      downloads_count
      comments_count
      description
      github_name
      url
      commits_count
    ]
  )
end
